"""Initial migration

Revision ID: 1f632964966c
Revises: 
Create Date: 2024-01-29 20:12:20.418857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f632964966c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadium',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('general_info', sa.Text(), nullable=False),
    sa.Column('year_established', sa.Integer(), nullable=False),
    sa.Column('maintenance_company', sa.String(length=50), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stadium')
    # ### end Alembic commands ###
