"""second migration

Revision ID: 33ac5aef1a28
Revises: 4a7b8666b292
Create Date: 2024-01-31 11:28:07.054564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ac5aef1a28'
down_revision = '4a7b8666b292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('repassword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repassword', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
